### ISSUE TITLE
Configure Watch App Parameters from Smartphone

### ISSUE THREAD

**Issue by Ynnz** [DanielBlomberg1/mimir#4]
Implement the functionality for configuring parameters on the smartwatch through the smartphone interface.

**Comment by xinyiPikachuG** [comment]
roughly achieved: 
in app setting activity, pressing the control button-> send csv file to watch, the csv file contains the JSON data of current setting parameters.
in watch setting activity, listen file receiving in create lifecycle-> receive file from app, and reflect it to app view.

haven't tested it, as might need physical watch for that.

more optimization points:
this method would generate many unnecessary csv file, I'll figure that out later.
If customer feel that pressing button to trigger is inconvenient, considering trigger the file setting after every user interaction in app setting page.
Considering synchronizing setting parameter from watch to mobile as initialization
currently the app side has fewer parameters than watch side, I will add the missing parameters after validating the main function.

**Comment by xinyiPikachuG** [comment]
add tab bar to setting page, separate local/watch setting data
add go back button to setting page
update file name, add "ECG,PPG,GSR" to Watch page, make sure ECG and GSR are not enabled at the same time
receive "ECG,PPG,GSR" in watch side, fix the reflect-to-view bug, make it works well
current  setting page:
![image](https://github.com/user-attachments/assets/e877f349-0bad-4b59-8d11-fe3aadfd7f6c)
![image](https://github.com/user-attachments/assets/089ff129-db60-42c5-bd3c-5df38d81f372)
